services:
  - type: web
    name: qala-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port 8000
    envVars:
      - key: SUPABASE_URL
        value: https://your-project.supabase.co
      - key: SUPABASE_KEY
        value: your_anon_key
      - key: DATABASE_URL
        value: postgresql://postgres:yourpassword@db.yourhost.supabase.co:5432/postgres
  